  POST http://localhost:3000/users/login HTTP/1.1
    Content-Type: application/json

    {
         "email":"shubhamsinghmor2312@gmail.com",
    "password":"Mummy4589"
}
###
POST http://localhost:3000/rides/create HTTP/1.1
Content-Type: application/json

{
  "pickup": "Delhi",
  "destination": "Mumbai",
  "vehicleType": "car"
}
###
GET http://localhost:3000/maps/get-suggestions HTTP/1.1
Content-Type:application/json
{
  "input":{
    "pickup": "Delhi",
    "destination": "Mumbai"
  }
}
###
POST http://localhost:3000/captains/register HTTP/1.1
Content-Type: application/json

{
  "fullname":{
                    "firstname": "shubham",
                    "lastname": "singh",
                },
                "email": "shubhamsinghmor2312@gmail.com",
                "password": "Mummy1",
                "vehicle":{
                    "color": "white",
                    "capacity": 4,
                    "plate": "1546g",
                    "vehicleType": "sedan",
                }
}